### ISSUE TITLE
virtual columns are not created

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/cattle#26]
Hi when adding a virtual column to the JSON file, it is actually not transformed: no triples are created.

E.g. from the example of the readthedocs-documentation:
```
  {
      "virtual": "true",
      "aboutUrl": "{Country}",
      "propertyUrl": "rdf:type",
      "valueUrl": "{% if Int > 100000 %}rich{% else %}poor{% endif %}"
    },
```

I've attached the example csv and json file (note remove the .txt. extension, misused it in order to be able to upload the files in git)

[imf_gdppc.csv-metadata.json.txt](https://github.com/CLARIAH/cattle/files/3876056/imf_gdppc.csv-metadata.json.txt)
[imf_gdppc.csv.txt](https://github.com/CLARIAH/cattle/files/3876057/imf_gdppc.csv.txt)

**Comment by albertmeronyo** [comment]
After an extensive dive into the code, the core of the issue is that now Python 3 comparison operators (`<`, `>`, etc.) are datatype sensitive, while Python 2 would happily evaluate expressions like `'3' > 3`. This is no longer the case, so calls to Jinja to render templates fail if no datatype information is supplied with the context variables.

I'd be very surprised that this particular example ever worked correctly with the example file (instances of `iish:rich` would surely be created, but not following the logic of the template expression).

There is no simple workaround other than falling back to the Python2 version. The proper solution is to pass down a datatype data structure to `render_pattern()` and use it to cast to proper types before rendering the template.

Opening an issue about this at https://github.com/CLARIAH/COW/issues/77
